version: "3.9"

services:

  db: 
    image: postgres:16
    container_name: rps-db
    environment:
      POSTGRES_DB: rpsgame
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    container_name: spring-backend
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    environment:
      - CHOKIDAR_USEPOLLING=true
    build: ./frontend
    container_name: react-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend