version: "3.9"

services:

  backend:
    build: ./backend
    container_name: spring-backend
    ports:
      - "8080:8080"

  frontend:
    environment:
      - CHOKIDAR_USEPOLLING=true
    build: ./frontend
    container_name: react-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend